pipeline{
    agent any
    stages{
        stage("Build stage"){
           parallel{
                stage("checkin stage"){
                    steps{
                        sh '''
                        echo "first stage"
                        '''
                    }
                }
                stage("deploy stage"){
                    steps{
                        sh '''
                        echo "deploy stage"
                        '''
                    }
                }
            
           }

        }
        
}
}