pipeline{
    agent { label 'pprod'}

    stages{
        stage("git ckeckout"){
            steps{
                git url:"https://github.com/Gotoman12/DevopsPractice-Arjun.git",branch:'dev'
            }
        }
        stage("complie"){
            steps{
                sh 'mvn compile'
            }
        }
         stage("test"){
            steps{
                sh 'mvn test'
            }
        }
         stage("package"){
            steps{
                sh 'mvn clean package'
            }
        }
    }
}