pipeline{
    agent {
        label 'pprd'
    }
    
    stages{
        stage("git-checkout"){
            steps{
                   git url:'https://github.com/Gotoman12/DevopsPractice-Arjun.git',branch:'dev'
            } 
        }
         stage("hostname"){
            steps{
                    sh 'hostname'
            }
        }
         stage("Disk space"){
            steps{
                    sh 'df -kh'
            }
        }
        stage("Disk Memory"){
            steps{
                    sh 'free -m'
            }
        }
         stage("CPU Utl"){
            steps{
                    sh 'top -dn1 | head -10'
            }
        }
    }
}