pipeline{
    agent none
    
    stages{
        stage("git-checkout"){
             agent {
            label "dev"
        }
            steps{
                   git url:'https://github.com/Gotoman12/DevopsPractice-Arjun.git',branch:'dev'
            } 
        }
         stage("pprod-hostname"){
                agent {
            label "pprod"
        }
            steps{
                    sh 'hostname'
            }
        }
         stage("Disk space"){
                agent {
            label "prod"
        }
            steps{
                    sh 'df -kh'
            }
        }
        stage("Disk Memory"){
            agent {
            label "dev"
        }
            steps{
                    sh 'free -m'
            }
        }
         stage("CPU Utl"){
            agent {
            label "pprod"
        }
            steps{
                    sh 'top -dn1 | head -10'
            }
        }
    }
}