pipeline{
    agent any
    stages{
        stage("Web Hook"){
            steps{
                sh '''
                echo "Hello World"
                '''
            }
        }
         stage("after-activation"){
            steps{
                sh '''
                echo "to World"
                '''
            }
        }
        stage("after-test"){
            steps{
                sh '''
                echo "to test"
                '''
            }
        }
    }
}